# docker-compose.yml

services:
  # Spring Boot 애플리케이션 서비스
  nexus-app:
    build: .
    container_name: nexus-spring-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
      - redis-cache
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/springproject
      SPRING_DATASOURCE_USERNAME: nexus_user
      SPRING_DATASOURCE_PASSWORD: nexus_password
      SPRING_DATA_REDIS_HOST: redis-cache
      SPRING_DATA_REDIS_PORT: 6379

  # NestJS 알림/채팅 서버 서비스
  notification-server:
    build:
      context: notification-server
      dockerfile: Dockerfile.dev
    container_name: nexus-notification-server
    ports:
      - "3000:3000"
    volumes:
      - ./notification-server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      # Docker 컨테이너에서 호스트 PC(로컬)의 Spring Boot에 접근하기 위한 주소
      - DATABASE_URL=http://host.docker.internal:8080/api/chat/messages

  # MySQL 서비스 정의
  mysql-db:
    image: mysql:8.0
    container_name: nexus-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: springproject
      MYSQL_USER: nexus_user
      MYSQL_PASSWORD: nexus_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  # Redis 서비스 정의
  redis-cache:
    image: redis:latest
    container_name: nexus-redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
