# 개발 환경용 Dockerfile.dev

FROM node:20-alpine
WORKDIR /usr/src/app

# 패키지 파일 복사
COPY package*.json ./

# 개발 의존성 포함 설치
RUN npm install

# 소스 코드 복사
COPY . .

# 개발 모드로 실행 (빌드 없이)
CMD ["npm", "run", "start:dev"] 